[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''function mod_chips(_chips)'''
position = "after"
payload = '''
if next(SMODS.find_card("j_blueatro_scoop")) then
  _chips = math.min(_chips, mult or 1)
end
'''
match_indent = true
